import { saveReflectionAction } from "@/app/(app)/actions";
import { requireUser } from "@/lib/auth/session";
import { getWeeklyReview } from "@/lib/life-os/service";
import { prisma } from "@/lib/db/prisma";
import { AskLifeOs } from "@/components/ask-life-os";
import { generateWeeklyCoachAction } from "./actions";
import type { WeeklyCoaching } from "@/lib/intelligence/coaching-schema";

export default async function WeeklyReviewPage() {
  const user = await requireUser();
  const [review, execution] = await Promise.all([getWeeklyReview(user.id), prisma.aIExecution.findFirst({ where: { userId: user.id, operation: "weekly_coaching" }, orderBy: { createdAt: "desc" } })]);
  const coach = execution?.output && typeof execution.output === "object" && "answer" in execution.output ? (execution.output as { answer: WeeklyCoaching }).answer : null;
  const improved = review.improved as string[]; const deteriorated = review.deteriorated as string[]; const neglected = review.neglected as Array<{ area: string; reason: string }>;
  return <div className="page"><AskLifeOs prompts={["What should I focus on this week?", "What has actually improved recently?"]}/><section className="hero compact"><div><p className="eyebrow">Weekly review</p><h2>A permanent snapshot of the week.</h2><p>{review.overallScore}/100 average. Strongest area: {review.strongestArea ?? "not clear yet"}.</p></div></section><form action={generateWeeklyCoachAction}><button>{coach ? "Use saved coaching interpretation" : "Generate coaching interpretation"}</button></form>{coach ? <section className="panel coaching-review"><p className="eyebrow">Coaching interpretation · {coach.confidence.replaceAll("_", " ")}</p><h3>{coach.weekInOneSentence}</h3><div className="weekly-signals"><Section title="Biggest win" values={coach.biggestWin ? [coach.biggestWin] : []}/><Section title="Biggest concern" values={coach.biggestConcern ? [coach.biggestConcern] : []}/><Section title="Next priorities" values={coach.priorities.map((item) => item.action)}/></div><div className="two-col"><Block title="What is working" values={coach.working}/><Block title="Possible limiters" values={coach.possibleLimiters} label="Hypothesis"/><Block title="Trade-offs" values={coach.tradeOffs} label="Pattern"/><Block title="Continue" values={coach.continue}/><Block title="Change" values={coach.change}/><Block title="Missing information" values={coach.missingInformation} label="Insufficient evidence"/></div><details className="panel"><summary>Why this conclusion?</summary><p className="section-description">This interpretation is grounded in the deterministic weekly snapshot: score, recorded signals, trajectory and neglected areas. It does not establish causation.</p></details></section> : null}<section className="weekly-signals"><Section title="What improved" values={improved}/><Section title="What deteriorated" values={deteriorated}/><Section title="Neglected" values={neglected.map((item) => item.area)}/></section><form action={saveReflectionAction} className="panel form"><label><span>Personal reflection</span><textarea name="reflection" rows={6} defaultValue={review.reflection ?? ""} placeholder="What explains the week, and what will change next?" /></label><div className="form-footer"><p>Your reflection remains attached to this weekly snapshot.</p><button>Store review</button></div></form></div>;
}
function Section({ title, values }: { title: string; values: string[] }) { return <section><p>{title}</p><strong>{values.length ? values.join(" · ") : "No significant signal"}</strong></section>; }
function Block({ title, values, label }: { title: string; values: string[]; label?: string }) { return values.length ? <section className="panel"><p className="eyebrow">{label ?? "Coaching"}</p><h3>{title}</h3>{values.map((value) => <p className="section-description" key={value}>{value}</p>)}</section> : null; }
