import { saveCheckInAction } from "@/app/(app)/actions";
import { requireUser } from "@/lib/auth/session";
import { getTodayView } from "@/lib/life-os/service";

export default async function CheckInPage() { const user = await requireUser(); const state = await getTodayView(user.id); const entries = new Map(state.entries.map((entry) => [entry.metricDefinitionId, entry])); return <div className="page narrow"><section className="hero compact"><div><p className="eyebrow">Daily check-in</p><h2>Under two minutes. Only useful signal.</h2><p>Leave a field blank when you do not know it. Missing data remains unknown.</p></div><div className="score simple"><strong>{state.score}</strong><span>current score</span></div></section><form action={saveCheckInAction} className="panel form"><div className="metric-grid">{state.metrics.map((metric) => <MetricInput key={metric.id} metric={metric} entry={entries.get(metric.id)} />)}</div><label><span>Short reflection</span><textarea name="reflection" rows={4} defaultValue={state.checkIn?.reflection ?? ""} placeholder="What explains today?" /></label><div className="form-footer"><p>Score and drift rules refresh after save.</p><button>Save check-in</button></div></form></div>; }

function MetricInput({ metric, entry }: { metric: { id: string; key: string; name: string; unit: string | null; valueType: string; selectOptions: unknown }; entry?: { valueNumber: number | null; valueText: string | null; valueBoolean: boolean | null } }) {
  const label = <span>{metric.name}{metric.unit ? ` · ${metric.unit}` : ""}</span>;
  if (metric.valueType === "BOOLEAN") return <label>{label}<select name={metric.key} defaultValue={entry?.valueBoolean == null ? "" : entry.valueBoolean ? "true" : "false"}><option value="">Unknown</option><option value="true">Yes</option><option value="false">No</option></select></label>;
  if (metric.valueType === "TEXT" || metric.valueType === "SELECT") return <label>{label}{metric.valueType === "SELECT" && Array.isArray(metric.selectOptions) ? <select name={metric.key} defaultValue={entry?.valueText ?? ""}><option value="">Choose</option>{metric.selectOptions.map(String).map((option) => <option key={option}>{option}</option>)}</select> : <input name={metric.key} defaultValue={entry?.valueText ?? ""} />}</label>;
  return <label>{label}<input name={metric.key} type="number" step={metric.valueType === "SCALE_1_10" || metric.valueType === "INTEGER" ? 1 : "any"} min={metric.valueType === "SCALE_1_10" ? 1 : undefined} max={metric.valueType === "SCALE_1_10" ? 10 : undefined} defaultValue={entry?.valueNumber ?? ""} /></label>;
}
