/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { describeDriftRule, formatSchedule, getSettingsView, scheduleDays } from "@/lib/life-os/settings";
import { moveAreaDown, moveAreaUp, removeArea, saveArea, saveHabit, saveKeyResult, saveMetric, saveNotification, saveObjective, saveRecurringAction, saveRule, saveSupplement } from "./actions";
import { getArchitectureView } from "@/lib/intelligence/service";

const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const field = (name: string, value?: string | number | null, placeholder?: string) => <input name={name} defaultValue={value ?? ""} placeholder={placeholder} />;
const check = (name: string, checked = false, label?: string) => <label className="toggle"><input name={name} type="checkbox" defaultChecked={checked} />{label ?? name}</label>;
const days = (selected: unknown) => <div className="days">{dayNames.map((name, value) => <label key={name}><input type="checkbox" name="days" value={value} defaultChecked={scheduleDays(selected).includes(value)} />{name}</label>)}</div>;

export default async function SettingsPage() {
  const user = await requireUser(); const [state, architecture] = await Promise.all([getSettingsView(user.id), getArchitectureView(user.id)]);
  return <div className="page settings-page">
    <section className="hero settings-hero"><div><p className="eyebrow">Advanced configuration</p><h2>Precise control, when you need it.</h2><p>Define where you are, where you want to be, and what matters enough to guide the system's decisions. This is your personal objective function, made explicit.</p></div><div className="config-score"><strong>{state.summary.weightTotal}%</strong><span>active score weighting</span></div></section>
    <section className="alignment-frame" aria-label="Alignment model"><p>Where I am</p><i>→</i><p>Where I want to be</p><i>→</i><p>What matters</p><i>→</i><strong>What Life OS optimises for</strong></section>
    <nav className="settings-nav" aria-label="Alignment sections">{[["direction", "Life direction"], ["areas", "Life areas"], ["objectives", "Objectives & OKRs"], ["score", "Score"], ["behaviours", "Behaviours"], ["metrics", "Metrics"], ["supplements", "Supplements"], ["actions", "Recurring actions"], ["drift", "Drift rules"], ["notifications", "Notifications"]].map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav>
    <section className="configuration-summary"><Summary label="Life areas" value={state.summary.areas} /><Summary label="Objectives" value={state.summary.objectives} /><Summary label="Key results" value={state.summary.keyResults} /><Summary label="Behaviours" value={state.summary.behaviours} /><Summary label="Metrics" value={state.summary.metrics} /><Summary label="Supplements" value={state.summary.supplements} /><Summary label="Recurring actions" value={state.summary.recurringActions} /><Summary label="Drift rules" value={state.summary.driftRules} /></section>

    <section id="direction" className="panel direction"><p className="eyebrow">Life direction</p><h3>The life this system is currently optimising towards</h3><p className="direction-intro">This is a direct reading of your active configuration, not a motivational interpretation.</p><div className="direction-grid">{state.areas.filter((area) => area.active).map((area) => <article key={area.id}><div><strong>{area.name}</strong><span>{area.weight}% of score</span></div><p>{area.description || "No description yet. Define why this area belongs in your life."}</p><ul>{area.objectives.filter((item) => item.active).map((objective) => <li key={objective.id}><Link href="#objectives">{objective.title}</Link>{objective.keyResults.map((result) => <small key={result.id}>{result.title}{result.target != null ? `: ${result.target}${result.unit ? ` ${result.unit}` : ""}` : ""}</small>)}</li>)}</ul><span className="alignment-actions"><Link className="text-link" href={`/alignment/${area.id}`}>Align this area</Link><Link className="text-link" href="#areas">Configure {area.name}</Link></span></article>)}</div></section>

    <SettingsSection id="areas" eyebrow="Foundation" title="Life areas" description="The durable domains you choose to protect. Weighting affects future score calculations only."><div className="config-list">{state.areas.map((area) => <details key={area.id}><summary><span><strong>{area.name}</strong><small>{area.active ? `${area.weight}% weighting` : "Inactive"}</small></span><span>Configure</span></summary><form action={saveArea} className="config-form"><input type="hidden" name="id" value={area.id} /><label>Name{field("name", area.name)}</label><label>Description<textarea name="description" defaultValue={area.description ?? ""} /></label><label>Score weighting (%) {field("weight", area.weight)}</label>{check("active", area.active, "Active life area")}<div className="form-actions"><button>Save area</button><button formAction={moveAreaUp} className="quiet">Move up</button><button formAction={moveAreaDown} className="quiet">Move down</button><button formAction={removeArea} className="danger">Delete safely</button></div></form></details>)}</div><details className="add-config"><summary>Add a life area</summary><form action={saveArea} className="config-form">{field("name", null, "e.g. Community") }<textarea name="description" placeholder="Why does this area matter?" />{field("weight", 0)}{check("active", true, "Active immediately")}<button>Create life area</button></form></details></SettingsSection>

    <SettingsSection id="objectives" eyebrow="Direction" title="Objectives & key results" description="Outcomes are the direction. Behaviours and recurring actions are the repeatable ways of moving toward them."><div className="config-list">{state.objectives.map((objective) => <details key={objective.id}><summary><span><strong>{objective.title}</strong><small>{objective.lifeArea.name} · {objective.active ? `Priority ${objective.priority}` : "Inactive"}</small></span><span>Configure</span></summary><form action={saveObjective} className="config-form"><input type="hidden" name="id" value={objective.id} /><label>Objective{field("title", objective.title)}</label><label>Description<textarea name="description" defaultValue={objective.description ?? ""} /></label><label>Life area<select name="lifeAreaId" defaultValue={objective.lifeAreaId}>{state.areas.map((area) => <option value={area.id} key={area.id}>{area.name}</option>)}</select></label><label>Priority (1 is highest){field("priority", objective.priority)}</label><label>Target date<input name="dueDate" type="date" defaultValue={objective.dueDate?.toISOString().slice(0, 10)} /></label>{check("active", objective.active, "Active objective")}<button>Save objective</button></form><div className="nested-config"><p className="eyebrow">Key results</p>{objective.keyResults.map((result) => <KeyResultForm key={result.id} result={result} objectives={state.objectives} metrics={state.metrics} />)}<KeyResultForm objectives={state.objectives} metrics={state.metrics} objectiveId={objective.id} /></div></details>)}</div><details className="add-config"><summary>Add an objective</summary><form action={saveObjective} className="config-form">{field("title", null, "Outcome to pursue")}<textarea name="description" placeholder="What does success mean?" /><select name="lifeAreaId">{state.areas.filter((area) => area.active).map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select>{field("priority", 3)}{check("active", true, "Active immediately")}<button>Create objective</button></form></details></SettingsSection>

    <SettingsSection id="score" eyebrow="Objective function" title="Score configuration" description="Future scores weight scheduled, score-relevant behaviours, supplements, and recurring actions by the Life Area you assign. Missing actions count as incomplete; missing metrics remain unknown and are excluded."><div className="score-config">{state.areas.filter((area) => area.active).map((area) => <div key={area.id}><strong>{area.name}</strong><span>{area.weight}%</span><small>{state.habits.filter((habit) => habit.active && habit.affectsScore && habit.lifeAreaId === area.id).map((habit) => habit.name).join(" · ") || "No score-relevant behaviour"}</small></div>)}</div><p className={state.summary.weightTotal === 100 ? "success-note" : "notice"}>Active weighting totals {state.summary.weightTotal}%. {state.summary.weightTotal === 100 ? "Balanced at 100%." : "Use Life Areas to bring this closer to 100%."}</p></SettingsSection>

    <SettingsSection id="behaviours" eyebrow="Leading actions" title="Behaviours & habits" description="A behaviour is a repeated action that moves an objective forward. It is not the outcome itself."><div className="config-list">{state.habits.map((habit) => <details key={habit.id}><summary><span><strong>{habit.name}</strong><small>{habit.lifeArea.name} · {formatSchedule(habit.schedules[0]?.daysOfWeek, habit.frequency)}</small></span><span>Configure</span></summary><HabitForm habit={habit} areas={state.areas} objectives={state.objectives} /></details>)}</div><details className="add-config"><summary>Add a behaviour</summary><HabitForm areas={state.areas} objectives={state.objectives} /></details></SettingsSection>

    <SettingsSection id="metrics" eyebrow="Signals" title="Metrics & targets" description="Choose the measurements worth collecting. Today’s check-in is generated from active metrics marked for daily check-in."><div className="input-value-list">{architecture.metrics.map((item)=><div key={item.metric.id}><strong>{item.metric.name}</strong><span className={`input-${item.value.toLowerCase().replace("_","-")}`}>{item.value.replace("_"," ")}</span><small>{item.message}</small></div>)}</div><div className="config-list">{state.metrics.map((metric) => <details key={metric.id}><summary><span><strong>{metric.name}</strong><small>{metric.category} · {metric.active ? metric.valueType : "Inactive"}</small></span><span>Configure</span></summary><MetricForm metric={metric} /></details>)}</div><details className="add-config"><summary>Add a custom metric</summary><MetricForm /></details></SettingsSection>

    <SettingsSection id="supplements" eyebrow="Protocol" title="Supplements & protocols" description="Changes apply to the current protocol. Each newly completed log keeps a snapshot of its dose and schedule."><div className="config-list">{state.supplements.map((supplement) => <details key={supplement.id}><summary><span><strong>{supplement.name}</strong><small>{supplement.active ? `${supplement.intendedDose ?? ""} ${supplement.doseUnit ?? ""} · ${formatSchedule(supplement.schedules[0]?.daysOfWeek, supplement.frequency)}` : "Inactive"}</small></span><span>Configure</span></summary><SupplementForm supplement={supplement} /></details>)}</div><details className="add-config"><summary>Add a supplement</summary><SupplementForm /></details></SettingsSection>

    <SettingsSection id="actions" eyebrow="Operating rhythm" title="Recurring actions" description="These are configurable recurring commitments, not historical task completions."><div className="config-list">{state.tasks.filter((task) => task.recurrenceRule).map((task) => <details key={task.id}><summary><span><strong>{task.title}</strong><small>{task.lifeArea?.name ?? "Unassigned"} · {formatSchedule(task.recurrenceRule?.daysOfWeek, task.recurrenceRule?.frequency)}</small></span><span>Configure</span></summary><RecurringForm task={task} areas={state.areas} objectives={state.objectives} /></details>)}</div><details className="add-config"><summary>Add a recurring action</summary><RecurringForm areas={state.areas} objectives={state.objectives} /></details></SettingsSection>

    <SettingsSection id="drift" eyebrow="Interventions" title="Drift rules" description="Each rule is both editable and explained in plain language. No threshold is hidden."><div className="config-list">{state.rules.map((rule) => { const config = rule.config as { threshold?: number; days?: number; recommendedAction?: string }; return <details key={rule.id}><summary><span><strong>{rule.name}</strong><small>{rule.active ? describeDriftRule(rule.config) : "Disabled"}</small></span><span>Configure</span></summary><form action={saveRule} className="config-form"><input type="hidden" name="id" value={rule.id} /><label>Rule name{field("name", rule.name)}</label><label>Score threshold{field("threshold", config.threshold ?? 60)}</label><label>Consecutive days{field("days", config.days ?? 3)}</label><label>Minimum corrective action<textarea name="recommendedAction" defaultValue={config.recommendedAction ?? ""} /></label>{check("active", rule.active, "Alerts enabled")}<p className="plain-rule">{describeDriftRule(config)}</p><button>Save drift rule</button></form></details>})}</div></SettingsSection>

    <SettingsSection id="notifications" eyebrow="Communication" title="Notification preferences" description="Control what the private Life OS can prepare for delivery. The default provider records messages rather than sending them externally."><div className="config-list">{state.notifications.map((item) => <form key={item.id} action={saveNotification} className="notification-row"><input type="hidden" name="id" value={item.id} /><span><strong>{item.eventType.replaceAll("_", " ")}</strong><small>{item.channel} notification</small></span>{check("enabled", item.enabled, "Enabled")}<select name="minSeverity" defaultValue={item.minSeverity}><option value="INFO">Info</option><option value="WATCH">Watch</option><option value="AT_RISK">At risk</option><option value="OFF_TRACK">Off track</option></select><button>Save</button></form>)}</div></SettingsSection>
  </div>;
}

function SettingsSection({ id, eyebrow, title, description, children }: { id: string; eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section id={id} className="panel settings-section"><p className="eyebrow">{eyebrow}</p><h3>{title}</h3><p className="section-description">{description}</p>{children}</section>; }
function Summary({ label, value }: { label: string; value: number }) { return <div><strong>{value}</strong><span>{label}</span></div>; }
function KeyResultForm({ result, objectives, metrics, objectiveId }: { result?: { id: string; title: string; description: string | null; objectiveId: string; metricDefinitionId: string | null; baseline: number | null; target: number | null; currentValue: number | null; unit: string | null; targetDirection: string; currentValueSource: string; dueDate: Date | null; qualitative: boolean; active: boolean }; objectives: Array<{ id: string; title: string }>; metrics: Array<{ id: string; name: string }>; objectiveId?: string }) { return <details className="mini-form"><summary>{result ? result.title : "Add key result"}</summary><form action={saveKeyResult} className="config-form"><input type="hidden" name="id" value={result?.id ?? ""} />{field("title", result?.title, "What evidence would show progress?")}<textarea name="description" defaultValue={result?.description ?? ""} placeholder="Optional context" /><select name="objectiveId" defaultValue={result?.objectiveId ?? objectiveId}>{objectives.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="metricDefinitionId" defaultValue={result?.metricDefinitionId ?? ""}><option value="">Manual / qualitative</option>{metrics.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{field("baseline", result?.baseline, "Baseline")}{field("target", result?.target, "Target")}{field("currentValue", result?.currentValue, "Current value")}{field("unit", result?.unit, "Unit")}<select name="targetDirection" defaultValue={result?.targetDirection ?? "INCREASE"}><option value="INCREASE">Increase</option><option value="DECREASE">Decrease</option><option value="MAINTAIN">Maintain</option></select><label>Deadline<input name="dueDate" type="date" defaultValue={result?.dueDate?.toISOString().slice(0, 10)} /></label>{check("qualitative", result?.qualitative, "Qualitative result")}{check("active", result?.active ?? true, "Active")}<button>{result ? "Save key result" : "Create key result"}</button></form></details> }
function HabitForm({ habit, areas, objectives }: { habit?: any; areas: any[]; objectives: any[] }) { return <form action={saveHabit} className="config-form"><input type="hidden" name="id" value={habit?.id ?? ""} />{field("name", habit?.name, "e.g. Training session")}<select name="lifeAreaId" defaultValue={habit?.lifeAreaId}>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><select name="objectiveId" defaultValue={habit?.objectiveId ?? ""}><option value="">No linked objective</option>{objectives.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>{field("targetCount", habit?.targetCount ?? 1)}<select name="targetPeriod" defaultValue={habit?.targetPeriod ?? "day"}><option value="day">Per day</option><option value="week">Per week</option></select><select name="frequency" defaultValue={habit?.frequency ?? "DAILY"}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option></select>{days(habit?.schedules?.[0]?.daysOfWeek)}{field("scoreWeight", habit?.scoreWeight ?? 1)}<textarea name="notes" defaultValue={habit?.notes ?? ""} placeholder="Why does this behaviour matter?" />{check("showToday", habit?.showToday ?? true, "Show on Today")}{check("affectsScore", habit?.affectsScore ?? true, "Affects score")}{check("participatesInDrift", habit?.participatesInDrift ?? false, "Participates in drift")}{check("active", habit?.active ?? true, "Active")}<button>{habit ? "Save behaviour" : "Create behaviour"}</button></form>; }
function MetricForm({ metric }: { metric?: any }) { return <form action={saveMetric} className="config-form"><input type="hidden" name="id" value={metric?.id ?? ""} />{field("name", metric?.name, "Metric name")}<textarea name="description" defaultValue={metric?.description ?? ""} placeholder="What does this measure?" />{field("category", metric?.category ?? "custom")} {field("unit", metric?.unit, "Unit")}<select name="valueType" defaultValue={metric?.valueType ?? "NUMBER"}>{["NUMBER", "INTEGER", "DECIMAL", "DURATION", "BOOLEAN", "SCALE_1_10", "SELECT", "TEXT"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select>{field("defaultTarget", metric?.defaultTarget, "Target")}{field("targetMin", metric?.targetMin, "Minimum")}{field("targetMax", metric?.targetMax, "Maximum")}<select name="targetDirection" defaultValue={metric?.targetDirection ?? "NONE"}><option value="NONE">No direction</option><option value="INCREASE">Increase</option><option value="DECREASE">Decrease</option><option value="RANGE">Target range</option></select><select name="frequency" defaultValue={metric?.frequency ?? "DAILY"}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="AS_NEEDED">As needed</option></select>{field("decimalPrecision", metric?.decimalPrecision ?? 0)}{check("showInCheckIn", metric?.showInCheckIn ?? true, "Show in daily check-in")}{check("showInDashboard", metric?.showInDashboard ?? true, "Show in dashboard trends")}{check("useInDrift", metric?.useInDrift ?? false, "Use in drift")}{check("useInScore", metric?.useInScore ?? false, "Use in score")}{check("important", metric?.important ?? false, "Important signal")}{check("active", metric?.active ?? true, "Active")}<button>{metric ? "Save metric" : "Create metric"}</button></form>; }
function SupplementForm({ supplement }: { supplement?: any }) { return <form action={saveSupplement} className="config-form"><input type="hidden" name="id" value={supplement?.id ?? ""} />{field("name", supplement?.name, "Supplement name")}{field("intendedDose", supplement?.intendedDose, "Dose")}{field("doseUnit", supplement?.doseUnit, "Unit")} {field("normalTime", supplement?.normalTime, "Normal time")}<select name="frequency" defaultValue={supplement?.frequency ?? "DAILY"}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="AS_NEEDED">As needed</option></select>{days(supplement?.schedules?.[0]?.daysOfWeek)}<label>Start date<input name="startDate" type="date" defaultValue={supplement?.startDate?.toISOString().slice(0, 10)} /></label><label>End date<input name="endDate" type="date" defaultValue={supplement?.endDate?.toISOString().slice(0, 10)} /></label><textarea name="notes" defaultValue={supplement?.notes ?? ""} placeholder="Protocol notes" />{check("active", supplement?.active ?? true, "Active")}<button>{supplement ? "Save protocol" : "Create supplement"}</button></form>; }
function RecurringForm({ task, areas, objectives }: { task?: any; areas: any[]; objectives: any[] }) { return <form action={saveRecurringAction} className="config-form"><input type="hidden" name="id" value={task?.id ?? ""} />{field("title", task?.title, "Recurring action")}<select name="lifeAreaId" defaultValue={task?.lifeAreaId ?? ""}><option value="">Unassigned</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><select name="objectiveId" defaultValue={task?.objectiveId ?? ""}><option value="">No linked objective</option>{objectives.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="priority" defaultValue={task?.priority ?? "SECONDARY"}>{["MOST_IMPORTANT", "CRITICAL", "SECONDARY", "OPTIONAL"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select><select name="frequency" defaultValue={task?.recurrenceRule?.frequency ?? "WEEKLY"}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option></select>{days(task?.recurrenceRule?.daysOfWeek)}{field("targetFrequency", task?.targetFrequency ?? 1)}{check("showToday", task?.showToday ?? true, "Show on Today")}{check("scoreRelevant", task?.scoreRelevant ?? true, "Affects score")}{check("active", task?.active ?? true, "Active")}<button>{task ? "Save recurring action" : "Create recurring action"}</button></form>; }
