"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { deriveInterviewProgress, type InterviewStage } from "@/lib/intelligence/interview-progress";

type Assertion={id:string;category:string;content:string;source:string;confidence:string};
type Message={id:string;role:string;content:string;clientTurnId?:string|null;turnStatus?:string;turnError?:string|null};
type Session={id:string;lifeArea:{name:string};messages:Message[];assertions:Assertion[]};
type Overall={id:string;name:string;state:string};
const labels:Record<string,string>={CURRENT:"Current reality",DESIRED:"Desired reality",MOTIVATION:"Motivations",PRIORITY:"Priorities",CONSTRAINT:"Constraints",ANTI_GOAL:"Anti-goals",OBSERVED:"Observed patterns",INFERRED:"Life OS thinks",TENSION:"Tensions",UNCERTAINTY:"Still unclear"};
const stageCopy:Record<InterviewStage,string>={EXPLORE:"Exploring",CLARIFY:"Clarifying",DEFINE:"Defining",CHALLENGE:"Testing the shape of it",SYNTHESISE:"Bringing it together",READY:"Ready to act"};

export function AlignmentConversation({initial,initialProgress,overall,hasStrategy}:{initial:Session;initialProgress:ReturnType<typeof deriveInterviewProgress>;overall:Overall[];hasStrategy:boolean}){
  const [session,setSession]=useState(initial); const [text,setText]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [updated,setUpdated]=useState(0); const input=useRef<HTMLTextAreaElement>(null); const draftKey=`life-os-alignment:${initial.id}`;
  const progress=useMemo(()=>deriveInterviewProgress(session.assertions,{current:initialProgress.dimensions.find(x=>x.key==="current")?.state==="CLEAR",desired:initialProgress.dimensions.find(x=>x.key==="desired")?.state==="CLEAR",constraints:initialProgress.dimensions.find(x=>x.key==="constraints")?.state==="CLEAR",measurement:initialProgress.dimensions.find(x=>x.key==="measurement")?.state==="CLEAR",strategy:hasStrategy}),[session.assertions,initialProgress,hasStrategy]);
  const question=[...session.messages].reverse().find(m=>m.role==="ASSISTANT")?.content??"What feels most important to understand about this area?";
  const failed=[...session.messages].reverse().find(m=>m.role==="USER"&&(m.turnStatus==="TIMED_OUT"||m.turnStatus==="FAILED"));
  useEffect(()=>{const saved=sessionStorage.getItem(draftKey);if(saved)setText(saved)},[draftKey]);
  useEffect(()=>{if(text)sessionStorage.setItem(draftKey,text);else sessionStorage.removeItem(draftKey)},[draftKey,text]);
  const submit=async(content=text,turnId=crypto.randomUUID())=>{if(!content.trim()||busy)return;const before=session.assertions.length;setBusy(true);setError("");try{const r=await fetch("/api/alignment/turn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.id,content,clientTurnId:turnId})});const data=await r.json();if(data.session)setSession(data.session);if(!r.ok)throw new Error(data.error);setSession(data);setText("");setUpdated(Math.max(0,data.assertions.length-before))}catch(e){setError(friendlyError(e instanceof Error?e.message:""))}finally{setBusy(false)}};
  const correct=async(id:string,intent:string)=>{const r=await fetch("/api/alignment/correction",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.id,assertionId:id,intent})});if(r.ok){setSession(s=>({...s,assertions:s.assertions.filter(a=>a.id!==id)}));setUpdated(0)}};
  return <section className="alignment-interview" aria-label={`Alignment interview for ${session.lifeArea.name}`}>
    <div className="interview-main">
      <div className="interview-orientation"><div><p className="eyebrow">Aligning {session.lifeArea.name}</p><h2>{stageCopy[progress.stage]}</h2></div><span>{progress.ready?"Enough is taking shape to review a strategy.":"One useful question at a time."}</span></div>
      <div className="interview-stage" aria-label="Interview progress"><span className="stage-name">{stageCopy[progress.stage]}</span><div className="stage-rail">{(["EXPLORE","CLARIFY","DEFINE","CHALLENGE","SYNTHESISE","READY"] as InterviewStage[]).map(stage=><i className={stage===progress.stage?"current":stageOrder(stage)<stageOrder(progress.stage)?"complete":""} key={stage} />)}</div><span className="stage-note">Understanding, not question count</span></div>
      {hasStrategy?<section className="aligned-state"><p className="eyebrow">Strategic maintenance</p><h3>This area has an active strategy.</h3><p>Review the model when your direction changes; use the current question to refine it without reopening a generic chat.</p><Link className="quiet button" href="#strategy">View strategy context</Link></section>:null}
      {progress.ready&&!hasStrategy?<section className="interview-synthesis"><p className="eyebrow">A coherent picture is emerging</p><h3>I have enough to begin shaping a strategy.</h3><p>Current reality, desired direction, constraints and a way to observe progress are now present. Review what Life OS understands, correct anything that is wrong, or build a pathway proposal.</p><div><Link className="button" href="/intelligence">Build my strategy</Link><button className="quiet" onClick={()=>input.current?.focus()}>Keep exploring</button></div></section>:null}
      <section className="question-card"><p className="eyebrow">The question Life OS needs answered now</p><h3>{question}</h3><details className="question-why"><summary>Why this question?</summary><p>{progress.reason}</p>{progress.next?<small>This helps Life OS define: {progress.next.label}.</small>:<small>This helps Life OS test whether the existing strategy still fits.</small>}</details><label className="alignment-input"><span>Your considered response</span><textarea ref={input} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey)){e.preventDefault();submit()}}} placeholder="Answer in your own words. Specific detail helps, but nuance matters more than perfect formatting." rows={6}/></label><div className="interview-submit"><button onClick={()=>submit()} disabled={busy||!text.trim()}>{busy?"Understanding your answer…":"Continue"}</button><small>⌘/Ctrl + Enter to continue</small></div></section>
      {busy?<p className="processing-state" role="status">Checking this against what Life OS already understands, then preparing the next question.</p>:null}
      {updated>0?<p className="understanding-update" role="status">Understanding updated: {updated} new strategic signal{updated===1?"":"s"} added.</p>:null}
      {error?<section className="interview-error" role="alert"><p className="eyebrow">I could not safely use that interpretation</p><h3>Your answer is saved.</h3><p>{error} You do not need to retype it.</p><div>{failed?<button onClick={()=>submit(failed.content,failed.clientTurnId||crypto.randomUUID())} disabled={busy}>Try again</button>:<button onClick={()=>input.current?.focus()}>Clarify what changed</button>}<button className="quiet" onClick={()=>input.current?.focus()}>Something changed</button></div></section>:null}
      <details className="conversation-history"><summary>Previous conversation and decisions</summary><div>{session.messages.map(m=><p key={m.id}><b>{m.role==="USER"?"You":m.role==="CORRECTION"?"Correction":"Life OS"}</b>{m.content}{m.turnStatus==="TIMED_OUT"||m.turnStatus==="FAILED"?<small>Saved · recoverable</small>:null}</p>)}</div></details>
    </div>
    <aside className="interview-context"><div className="context-heading"><p className="eyebrow">Live understanding</p><h3>What Life OS knows so far</h3><span>{session.assertions.length?"Open any statement to correct it.":"Still building the first useful picture."}</span></div><div className="dimension-list">{progress.dimensions.slice(0,5).map(item=><span key={item.key} className={item.state.toLowerCase()}><b>{item.label}</b><small>{item.state==="CLEAR"?"Understood":item.state==="DEVELOPING"?"Developing":"Still unclear"}</small></span>)}</div><details className="overall-alignment"><summary>Your overall alignment</summary>{overall.map(item=><Link href={`/alignment/${item.id}`} key={item.id}><span>{item.name}</span><small>{item.state.replaceAll("_"," ")}</small></Link>)}</details><div className="understanding-groups">{Object.entries(labels).map(([category,label])=>{const items=session.assertions.filter(a=>a.category===category);return items.length?<section key={category}><p>{label}</p>{items.map(a=><article key={a.id} className={`truth-${a.source.toLowerCase()}`}><span>{a.source==="STATED"?"You said":a.source==="OBSERVED"?"Life OS observed":"Life OS thinks"}</span><strong>{a.content}</strong>{a.source==="INFERRED"?<small>Confidence: {a.confidence.replaceAll("_"," ")}</small>:null}<div><button className="quiet" onClick={()=>correct(a.id,"WRONG")}>That’s wrong</button><button className="quiet" onClick={()=>correct(a.id,"CLARIFY")}>Clarify</button>{a.source==="INFERRED"?<button className="quiet" onClick={()=>correct(a.id,"THIS IS ONLY A HYPOTHESIS")}>Only a hypothesis</button>:null}</div></article>)}</section>:null})}</div><details className="uncertainty-note"><summary>What remains uncertain?</summary><p>{progress.next?`${progress.next.label} is the next material unknown. Life OS will stop exploring when another answer is unlikely to change the strategy.`:"The current model is coherent. The next step is a strategic review, not more questioning for its own sake."}</p></details></aside>
  </section>;
}
function stageOrder(stage:InterviewStage){return ["EXPLORE","CLARIFY","DEFINE","CHALLENGE","SYNTHESISE","READY"].indexOf(stage)}
function friendlyError(message:string){if(message.includes("timed out"))return "Life OS took too long to respond.";if(message.includes("verified")||message.includes("validation"))return "Part of the interpretation conflicted with information already stored in this Alignment.";return "Life OS could not complete a safe interpretation right now."}
