export type Confidence = "HIGH" | "MEDIUM" | "LOW" | "INSUFFICIENT_DATA";
export type InputValue = "REQUIRED" | "USEFUL" | "LOW_VALUE" | "UNCONNECTED";
export type Signal = { date: Date; value: number };

export function confidenceFor(points: Signal[]): Confidence { if (points.length < 2) return "INSUFFICIENT_DATA"; const age = (Date.now() - points.at(-1)!.date.getTime()) / 86_400_000; if (points.length >= 10 && age <= 7) return "HIGH"; if (points.length >= 5 && age <= 14) return "MEDIUM"; return "LOW"; }
export function classifyInput(input: { pathwayLinked: boolean; scoreRelevant: boolean; driftRelevant: boolean; loggedCount: number; frequency: string }) : InputValue { if (input.pathwayLinked) return "REQUIRED"; if (input.scoreRelevant || input.driftRelevant) return "USEFUL"; if (input.loggedCount >= 5 && input.frequency === "DAILY") return "LOW_VALUE"; return "UNCONNECTED"; }
export function trend(points: Signal[]) { if (points.length < 2) return null; const sorted=[...points].sort((a,b)=>a.date.getTime()-b.date.getTime()); const delta=sorted.at(-1)!.value-sorted[0].value; return { delta, direction: delta > 0 ? "UP" : delta < 0 ? "DOWN" : "FLAT", confidence: confidenceFor(points) }; }
export function detectTradeOff(input: { work: Signal[]; sleep: Signal[]; relationships: Signal[] }) { const work=trend(input.work), sleep=trend(input.sleep), relationships=trend(input.relationships); if (!work || work.direction !== "UP") return null; const declines=[sleep?.direction === "DOWN" ? "sleep" : null, relationships?.direction === "DOWN" ? "relationship attention" : null].filter(Boolean); return declines.length ? { title: `Work progress and ${declines.join(" + ")} are moving in different directions.`, confidence: work.confidence === "HIGH" && (sleep?.confidence === "HIGH" || relationships?.confidence === "HIGH") ? "MEDIUM" as Confidence : "LOW" as Confidence, explanation: "These changes are occurring together in the available data; this does not establish causation." } : null; }
export function rankPriorities<T extends { importance: number; trajectory: string; proximity: number; urgency: number; neglect: number; impact: number }>(items: T[]) { const weight=(item:T)=>item.importance*3+item.proximity*2+item.urgency*2+item.neglect*2+item.impact+(item.trajectory === "BEHIND" || item.trajectory === "STALLED" ? 5 : 0); return [...items].sort((a,b)=>weight(b)-weight(a)).slice(0,3); }
export function weeklyRecommendation(input: { improved: string[]; deteriorated: string[]; neglected: string[] }) { if (!input.deteriorated.length && !input.neglected.length) return { title: "No change required", detail: "Available evidence supports continuing the current strategy." }; if (input.neglected.length) return { title: `Protect ${input.neglected[0]}`, detail: "This area received no meaningful recorded attention this week." }; return { title: `Stabilise ${input.deteriorated[0]}`, detail: "This was the clearest deteriorating signal in the available data." }; }
