import Link from "next/link";
import { addTaskAction, completeAction } from "@/app/(app)/actions";
import { requireUser } from "@/lib/auth/session";
import { dateLabel } from "@/lib/life-os/date";
import { getTodayView } from "@/lib/life-os/service";

export default async function TodayPage({ searchParams }: { searchParams: Promise<{ checkedIn?: string }> }) {
  const user = await requireUser(); const state = await getTodayView(user.id); const params = await searchParams;
  const done = (type: "task" | "habit" | "supplement", targetId: string) => type === "task" ? state.taskCompletions.some((item) => item.taskId === targetId && item.state === "COMPLETED") : type === "habit" ? state.habitCompletions.some((item) => item.habitId === targetId && item.state === "COMPLETED") : state.supplementLogs.some((item) => item.supplementId === targetId && item.state === "COMPLETED");
  return <div className="page">{params.checkedIn ? <p className="notice">Check-in saved. Today’s score has been recalculated.</p> : null}<section className="hero"><div><p className="eyebrow">{dateLabel(state.date)}</p><h2>{state.summary}</h2><p>Start with what restores capacity, then move the one meaningful commitment.</p><div className="actions"><Link href="/check-in" className="button">Open check-in</Link><Link href="/dashboard" className="button secondary">View trajectory</Link></div></div><Score score={state.score} status={state.status} parts={state.parts} /></section>{state.alerts.length ? <section className="panel alert-grid"><div><p className="eyebrow">Intervention</p><h3>Drift requiring attention</h3></div>{state.alerts.map((alert) => <article key={alert.id} className="alert"><strong>{alert.title}</strong><p>{alert.explanation}</p><small>{alert.observedValue} observed, {alert.expectedValue} expected</small><p>{alert.recommendedAction}</p></article>)}</section> : null}<section className="two-col"><div className="panel"><div className="section-head"><div><p className="eyebrow">Act</p><h3>Essential actions</h3></div><form action={addTaskAction} className="add-task"><input name="title" aria-label="New task" placeholder="Add an essential action" required /><select name="priority" defaultValue="SECONDARY"><option value="MOST_IMPORTANT">Most important</option><option value="CRITICAL">Critical</option><option value="SECONDARY">Secondary</option></select><button aria-label="Add task">+</button></form></div><div className="rows">{state.tasks.map((task) => <Row key={task.id} title={task.title} meta={task.priority.replaceAll("_", " ")} complete={done("task", task.id)} action={completeAction.bind(null, "task", task.id)} />)}</div></div><div className="panel"><p className="eyebrow">Health protocol</p><h3>Supplements due today</h3><div className="rows">{state.supplements.map((item) => <Row key={item.id} title={item.name} meta={`${item.intendedDose ?? ""} ${item.doseUnit ?? ""} ${item.normalTime ? `· ${item.normalTime}` : ""}`} complete={done("supplement", item.id)} action={completeAction.bind(null, "supplement", item.id)} />)}</div></div></section><section className="panel"><p className="eyebrow">Leading behaviours</p><h3>Score drivers</h3><div className="card-grid">{state.habits.map((item) => <Row key={item.id} title={item.name} meta={item.lifeArea.name} complete={done("habit", item.id)} action={completeAction.bind(null, "habit", item.id)} />)}</div></section></div>;
}

function Score({ score, status, parts }: { score: number; status: string; parts: Array<{ label: string; expected: number; completed: number; weight: number }> }) { return <aside className="score"><strong>{score}</strong><span>/100 · {status.replaceAll("_", " ")}</span>{parts.map((part) => <div key={part.label} className="score-part"><span>{part.label}</span><small>{part.completed}/{part.expected}</small><i><b style={{ width: `${part.expected ? part.completed / part.expected * 100 : 100}%` }} /></i></div>)}</aside>; }
function Row({ title, meta, complete, action }: { title: string; meta: string; complete: boolean; action: () => Promise<void> }) { return <form action={action} className={`row ${complete ? "complete" : ""}`}><button type="submit" aria-label={`Complete ${title}`} disabled={complete}>{complete ? "✓" : ""}</button><span><strong>{title}</strong><small>{meta}</small></span></form>; }
