import { requireUser } from "@/lib/auth/session";
import { getSettingsView } from "@/lib/life-os/settings";
import { getArchitectureView, getIntelligenceView } from "@/lib/intelligence/service";
import { generatePathwayAction, recalculatePathwayAction, resolveProposalAction } from "./actions";
import { AskLifeOs } from "@/components/ask-life-os";

export default async function IntelligencePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser(); const [view, settings, architecture, params] = await Promise.all([getIntelligenceView(user.id), getSettingsView(user.id), getArchitectureView(user.id), searchParams]);
  return <div className="page intelligence-page"><section className="intelligence-hero"><p className="eyebrow">Navigation system</p><h2>Where you are. Where you are going. What matters now.</h2><p>Pathways are proposed from your baseline, destination and constraints. You approve every meaningful change.</p></section>{params.error ? <p className="notice" role="alert">{params.error}</p> : null}
    <section className="panel"><p className="eyebrow">New intelligent goal</p><h3>Build a pathway, not another dashboard.</h3><form action={generatePathwayAction} className="pathway-form"><label>Objective<select name="objectiveId">{settings.objectives.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.lifeArea.name} · {item.title}</option>)}</select></label><label>Where are you now?<textarea required name="currentDescription" placeholder="e.g. 5K in 30 minutes" /></label><label>Where do you want to be?<textarea required name="desiredDescription" placeholder="e.g. 5K under 20 minutes" /></label><label>Current measured value<input name="baselineValue" inputMode="decimal" placeholder="30" /></label><label>Desired measured value<input name="targetValue" inputMode="decimal" placeholder="20" /></label><label>Unit<input name="unit" placeholder="minutes" /></label><label>Direction<select name="direction"><option value="DECREASE">Lower is better</option><option value="INCREASE">Higher is better</option></select></label><label>Desired date <input type="date" name="desiredDate" /></label><label className="wide">Constraints / preferences<textarea name="constraints" placeholder="Maximum 4 runs per week. Keep 3 strength sessions. Avoid excessive injury risk." /></label><button>Generate pathway proposal</button></form></section>
    {view.proposals.length ? <section className="proposal-stack"><p className="eyebrow">Awaiting your approval</p>{view.proposals.map((proposal) => <article key={proposal.id} className="proposal"><div><span>Proposed change</span><h3>{proposal.title}</h3><p>{proposal.rationale}</p><small>{proposal.provider} · {proposal.confidence.replaceAll("_", " ")}</small></div><form action={resolveProposalAction}><input type="hidden" name="proposalId" value={proposal.id} /><button name="decision" value="accept">Accept pathway</button><button className="quiet" name="decision" value="dismiss">Dismiss</button></form></article>)}</section> : null}
    <section className="pathway-list"><p className="eyebrow">Active routes</p>{view.pathways.length ? view.pathways.map((pathway) => { const next = pathway.milestones.find((item) => item.status === "ACTIVE"); const snapshot = pathway.trajectorySnapshots[0]; return <article className="pathway-card" key={pathway.id}><AskLifeOs pathwayId={pathway.id} prompts={pathway.trajectoryStatus==="ON_TRACK"?["What is driving progress?","Is anything worth changing?"]:["Why am I behind?","How do I reach the next milestone faster?"]}/><div className="pathway-top"><div><span>{pathway.objective.lifeArea.name}</span><h3>{pathway.objective.title}</h3></div><strong>{snapshot?.progressPercent != null ? `${Math.round(snapshot.progressPercent)}%` : "—"}</strong></div><div className="state-line"><span>Current: {pathway.currentDescription}</span><span>Desired: {pathway.desiredDescription}</span></div><div className="metric-binding"><b>Progress signal</b>{pathway.metrics.length ? pathway.metrics.map((item) => <span key={item.id}>{item.metricDefinition.name} · {item.metricDefinition.frequency.toLowerCase()} · {item.rationale}</span>) : <span>Awaiting your approved metric binding.</span>}</div><div className="next-milestone"><p>Next milestone</p><h3>{next?.title ?? "No measurable milestone yet"}</h3><span>{snapshot?.status.replaceAll("_", " ") ?? "INSUFFICIENT DATA"} · {snapshot?.confidence.replaceAll("_", " ") ?? "INSUFFICIENT DATA"}</span><small>{snapshot?.basis ?? "Add a baseline and metric observations to produce an estimate."}</small></div><div className="milestone-rail">{pathway.milestones.map((milestone) => <span key={milestone.id} className={milestone.status.toLowerCase()}>{milestone.title}</span>)}</div>{pathway.actions.map((action) => <div className="pathway-action" key={action.id}><strong>Today: {action.title}</strong><small>{action.rationale}</small></div>)}<form action={recalculatePathwayAction}><input type="hidden" name="pathwayId" value={pathway.id} /><button className="quiet">Recalculate from real data</button></form></article>; }) : <p className="empty">No pathways yet. Existing objectives remain unchanged until you add a baseline and desired state.</p>}</section>
    <section className="panel architecture"><p className="eyebrow">Life architecture</p><h3>Why the system asks for each input.</h3><p className="section-description">Open an area to trace its configured relationship from life direction to today’s data. This is an explanatory map, not a decorative graph.</p>{architecture.areas.map((area)=><details key={area.id}><summary><span>{area.name}</span><small>{area.objectives.length} objective{area.objectives.length===1?"":"s"}</small></summary><div className="architecture-chain">{area.objectives.map((objective)=>{const pathway=architecture.pathways.find((item)=>item.objectiveId===objective.id);const habits=architecture.habits.filter((item)=>item.objectiveId===objective.id);const metrics=pathway?.metrics.map((binding)=>architecture.metrics.find((item)=>item.metric.id===binding.metricDefinitionId)).filter(Boolean)??[];return <article key={objective.id}><b>Objective: {objective.title}</b><span>Desired state: {pathway?.desiredDescription??"Needs pathway setup"}</span><span>Next milestone: {pathway?.milestones.find((item)=>item.status==="ACTIVE")?.title??"Not established"}</span><span>Metrics: {metrics.length?metrics.map((item)=>item!.metric.name).join(" · "):"No bound progress metric"}</span><span>Behaviours: {habits.length?habits.map((item)=>item.name).join(" · "):"No linked behaviour"}</span><small>Today’s input → behaviour → milestone → objective. Missing links remain visible rather than inferred.</small></article>})}</div></details>)}</section>
    <section className="two-col"><div className="panel"><p className="eyebrow">Observed</p><h3>Evidence-backed insights</h3>{[...view.insights,...architecture.insights].length ? [...view.insights,...architecture.insights].map((item,index) => <article className="intelligence-row" key={`${item.title}-${index}`}><strong>{item.title}</strong><p>{item.explanation}</p><small>{item.confidence.replaceAll("_", " ")}</small></article>) : <p className="empty">No meaningful change detected yet.</p>}</div><div className="panel"><p className="eyebrow">Smallest useful intervention</p><h3>Recommendations</h3>{view.recommendations.length ? view.recommendations.map((item) => <article className="intelligence-row" key={item.id}><strong>{item.title}</strong><p>{item.explanation}</p><small>{item.confidence.replaceAll("_", " ")}</small></article>) : <p className="empty">No recommendation yet. The system will prefer “continue” when the available evidence supports it.</p>}</div></section>
  </div>;
}
